language: node_js
node_js:
  - 10
  - 11
  - 12
  - 13
  - 14

os:
  - linux
  - windows
  - osx

cache: npm

install:
  - npm install

script:
  - npm run test

after_success:
  - bash <(curl -s https://codecov.io/bash) -Z -v
